### ISSUE TITLE
Offer via Debian repository

### ISSUE THREAD

**Issue by PanderMusubi** [mopidy/mopidy-youtube#44]
Please offer Mopidy-YouTube via http://apt.mopidy.com/ so that users can install all Mopidy extensions with apt-get and are guaranteed that all dependencies van versions are in order. Most other extensions are already available on this repository, so adding this one would be a step up and reach more end-users. See also https://discuss.mopidy.com/t/add-mopidy-somafm-to-dep-repo/809

**Comment by kingosticks** [comment]
See https://github.com/pimusicbox/pimusicbox/issues/308

**Comment by jodal** [comment]
I've recently packages mopidy-youtube and it is available on apt.mopidy.com as well as in Debian unstable, testing and Ubuntu 15.10. The problem is, the package is broken because the dependency python-pafy has removed the Python 2.7 support from its package. This is reported as a bug at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=795085, but I've received no response so far.

**Comment by dz0ny** [comment]
joda we could vendor pafy since it is only wrapper for youtube-dl now

**Comment by jodal** [comment]
That wouldn't pass Debian review.

**Comment by dz0ny** [comment]
but requests, setuptools does the same...

**Comment by jodal** [comment]
And it is frowned upon, but accepted since they are needed to bootstrap pip (and Python which now bundles pip).
